### DISCUSSION TITLE
UI Shell wrong behavior

### DISCUSSION THREAD

**Discussion by hrstoyanov** [carbon-design-system/carbon-for-ibm-dotcom#11087] [Q&A]
Hello,
I am new to IBM Carbon. I try the WebComponent v2 (latest) version for my app skeleton and noticed that if I copy any UI Shell [example from the docs ](https://web-components.carbondesignsystem.com/?path=/docs/components-ui-shell--header-base-w-navigation-actions) pate it, and give it a try, the side navigation misbehaves: when I expand it enough  (at width breakpoint 1055px, I think), the header links start to show , but the side navigation does not disappear! **Is this a bug/bad documenttion**?

The weird thing is that you do not see this behavior when you try this in the storybook ...

I tried to fix this with the below, but it does not work:
```css
 @media (width > 1550) {
            cds-side-nav {
                display: none;
            }
            cds-side-nav-items {
                display: none;
            }
        } 
```
