### ISSUE TITLE
[Web components]: update all component styles to remove FOUC

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#10607]
Currently all web components are prone to FOUC (flash of unstyled content). Until now user would need to address this on the application side. The issue is many users are unaware of the fix, and our documentation is not very well exposed. The solution is to add the fix to all component styles, e.g.

```css
dds-background-media:not(:defined) {
  display: none;
}
```
