### ISSUE TITLE
What is the recommendation to add a footer when using the ui-shell?

### ISSUE THREAD

**Issue by abdonrd** [carbon-design-system/carbon-for-ibm-dotcom#10742]
### Summary

Live demo: https://stackblitz.com/edit/vitejs-vite-j8kfde?file=index.html

In mobile it's working really well:

![x](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/c81a12b6-9df4-42c6-9fbf-50f78815131d)

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/e6067ce0-ab66-4be5-a1ec-a2ae90510941

Notice that we had to add this CSS:

```css
main {
  margin-top: 3rem; /* cds-header width */
}

@media (min-width: 65.98rem) {
  main {
    margin-left: 16rem; /* cds-side-nav width */
  }
}
```

But on desktop, the footer is hidden under the `cds-side-nav`:

![x](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/74bbd72c-441d-4239-9a71-aa0364289590)

Instead of:

![x](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/d79804e4-2a08-46b9-a6d6-992b83da30ed)

### Name and organization

IBM Quantum

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues
