### ISSUE TITLE
scss compile to css error

### ISSUE THREAD

**Issue by lpkobamn** [carbon-design-system/carbon-for-ibm-dotcom#11867]
### Summary

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/styles/scss/ibm-dotcom-styles.css
```scss
/* Error: Can't find stylesheet to import.
 *   ,
 * 8 | @use '@carbon/styles/scss/config' as *;
 *   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 *   '
 *   scss/components/audio-player/_audio-player.scss 8:1  @forward
 *   scss/components/audio-player/_index.scss 8:1         @use
 *   scss/ibm-dotcom-styles.scss 13:1                     root stylesheet */

body::before {
  display: block;
  padding: 1em;
  border-block-end: 2px solid #000000;
  content: "Error: Can't find stylesheet to import.\a   \2577 \a 8 \2502  @use '@carbon/styles/scss/config' as *;\a   \2502  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\a   \2575 \a   scss/components/audio-player/_audio-player.scss 8:1  @forward\a   scss/components/audio-player/_index.scss 8:1         @use\a   scss/ibm-dotcom-styles.scss 13:1                     root stylesheet";
  font-family: 'Source Code Pro', 'SF Mono', Monaco, Inconsolata, 'Fira Mono',
    'Droid Sans Mono', monospace;
  margin-block-end: 1em;
  white-space: pre;
}
```

I tried to compile using the following code but got this error.

### Name and organization

Jacob

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues
